# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registereduser',
            name='note_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registereduser',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
