# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(default='Hello', max_length=25),
            preserve_default=False,
        ),
    ]
