# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-22 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='goal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_clothing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_food',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_medical',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_misc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_repairs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_taxes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_transport',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='m_utilities',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spent_10',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spent_15',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spent_20',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spent_25',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spent_30',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='spent_5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_clothing',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_food',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_medical',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_misc',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_repairs',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_taxes',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_transport',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='t_utilities',
            field=models.FloatField(default=0),
        ),
    ]
